export const productName = 'LGPD Checklist'
export const url = 'http://lgpd-checklist.magrathealabs.com'
export const description = 'Entrar em conformidade com a LGPD não precisa ser complicado. Essa é uma checklist básica que você pode utilizar para aumentar sua conformidade com a lei.'
export const keywords = 'LGPD, Privacidade, Dados, Brasil, Compliance, Conformidade, LGPD Checklist, LGPD Compliance, Conformidade LPGD, Segurança, Lei Geral de Proteção de Dados Pessoais, Operador, Controlador'
export const title = 'LGPD Checklist - Checklist de Conformidade com a LGPD'
export const twitter = '@laurogripa'
export const imagePreview = url + '/preview.png'
